# Generated by Django 3.2.8 on 2021-10-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20211025_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='taxNumber',
            new_name='tinNumber',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='taxNumber',
            new_name='tinNumber',
        ),
        migrations.RemoveField(
            model_name='client',
            name='province',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='province',
        ),
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.CharField(blank=True, choices=[('Greater Accra', 'Greater Accra'), ('Eastern', 'Eastern'), ('Western', 'Western'), ('Western North', 'Western North'), ('Oti Region', 'Oti Region'), ('Ashanti', 'Ashanti'), ('Ahafo', 'Ahafo'), ('Upper West', 'Upper West'), ('Upper East', 'Upper East'), ('North East', 'North East'), ('Bono East', 'Bono East'), ('Ahafo', 'Ahafo'), ('Savannah', 'Savannah'), ('Northern', 'Northern'), ('Volta', 'Volta'), ('Central', 'Central')], max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='region',
            field=models.CharField(blank=True, choices=[('Greater Accra', 'Greater Accra'), ('Eastern', 'Eastern'), ('Western', 'Western'), ('Western North', 'Western North'), ('Oti Region', 'Oti Region'), ('Ashanti', 'Ashanti'), ('Ahafo', 'Ahafo'), ('Upper West', 'Upper West'), ('Upper East', 'Upper East'), ('North East', 'North East'), ('Bono East', 'Bono East'), ('Ahafo', 'Ahafo'), ('Savannah', 'Savannah'), ('Northern', 'Northern'), ('Volta', 'Volta'), ('Central', 'Central')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('¢', 'GHS'), ('$', 'USD')], default='R', max_length=100),
        ),
    ]
