# Generated by Django 3.2.8 on 2021-10-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_rename_setting_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'Settings'},
        ),
    ]
